resources/css/style.css
search.html

Changed visual appearance of block quote and <kbd>, added search terms and updated search button.

Fix visual bugs.

---

modules/transform.xql
resources/js/page/view.js
view.html

The nonsense of generating all of the UI in XQuery is starting to get to me. I wish I had done it all a different way. Oh well.

Add some controls to the UI

---

list-nocache.html
map.html
modules/app.xql
modules/transform.xql
reports.html
resources/css/style.css
resources/js/bootstrap-table-addrbar.js
resources/js/d3.visualization.js
resources/js/list.js
resources/sass/_color.scss
resources/sass/style.scss
templates/page.html
view.html

Disabled a bunch of old JS pending removal. Fixed visual bugs: buttons, etc. Added better search to list.html, added D3 map to reports.html

Mostly style and D3 changes.

---

modules/transform.xql
resources/css/style.css
resources/js/page/view.js
resources/sass/style.scss

Just a couple CSS fixes; ignore the matches stuff for now.

Fixed visual bugs in tabs, tested experimental code for matches

---

about.html
compare.html
contact.html
contributors.html
export.html
index.html
license.html
list-nocache.html
map.html
networks.html
resources/js/d3.visualization.js
search.html
templates/page.html

Update the content on the static pages, following the google doc. 
There is one javascript change, do the d3 map visualization. I added the map wrapper to the HTML page, rather than having d3 append it. Otherwise the map kept showing up at the bottom of the page.

update the content.

---

list-nocache.html
resources/css/style.css
resources/sass/style.scss

Fixed tables on mobile.

---

resources/css/style.css
resources/sass/style.scss

fixed regression bug related to desktop width

---

modules/app.xql
resources/css/style.css
resources/sass/_mixins.scss
resources/sass/style.scss

This pull requests adds classes to the app.xql to style the gallery to address issue #26. 
New classes added:
* .gallery
* .img-tile
It also adds a zoom hover effect for images to provide visual feedback that they are clickable.

Flex fix for issue #26

---

modules/app.xql
resources/js/list.js

Manually configure the table filters in list.html

make dates unique.

---

modules/app.xql

Change lengths to counts

---

modules/app.xql
modules/document.xql
resources/css/style.css
resources/js/list.js
resources/js/page/compare-docs.js
resources/js/page/compare.js
resources/sass/style.scss
view.html

Remove the sorting options and streamline the filters
a little bit.
Add a date modified field for each report. The updated
metadata is set automatically by the text matching
tools when writing the report to disk.

Two small changes.

---

about.html
contact.html
contributors.html
search.html

Minor changes (4 changes) to Wilde Trials About content

WIdle Trails About Content

---

export.html
modules/app.xql
modules/export.xql
modules/stats.xql
templates/page.html

fixes sfu-dhil/wilde#53
fixes sfu-dhil/wilde#54
fixes sfu-dhil/wilde#55
fixes sfu-dhil/wilde#56
Cherry pick a few things from sfu-dhil/wilde#57
Remove the match type from data exports.

Fix a bunch of small things.

---

city-details.html
compare-docs.html
date-details.html
language-details.html
modules/app.xql
newspaper-details.html
region-details.html
resources/js/page/compare.js

Put the computed difference in a paragraph.

---

city-details.html
city-nocache.html
date-details.html
date-nocache.html
language-details.html
language-nocache.html
networks.html
region-details.html
region-nocache.html

Made fixes to markup on these report pages.

Fixed Markup on reports pages

---

README.md
modules/app.xql
resources/css/style.css
resources/sass/_mixins.scss
resources/sass/style.scss

* Add a calendar display
* Fix up some mobile viewing issues
* Add some documentation

Wilde fixes and updates

---

documentation.html
templates/page.html

* Adds a new documentation page (`documentation.html`)
* Changes the link for the documentation in the footer

Documentation

---

about.html
compare-docs.html
compare.html
curation.html
documentation.html
export.html
gallery.html
measure.html
networks.html
source-details.html
source-nocache.html
view.html

You should see the updates now.

Most recent updates

---

curation.html

curation.html

---

documentation.html
export.html

Added bullet points to the documentation. Too many bullet points?

Changes to documentation

---

modules/app.xql
templates/page.html

- Fix publisher link in breadcrumb.
fixes sfu-dhil/wilde#127
- Adjust footer
fixes sfu-dhil/wilde#128
- Add query parameters to jump to page widget as hidden inputs.
fixes sfu-dhil/wilde#129

Fix some small bugs.

---

index.html
modules/app.xql
modules/csv.xql
modules/export.xql
resources/css/style.css
resources/js/page/search.js
resources/sass/style.scss
search.html

fixes sfu-dhil/wilde#143
Header should be region not language
fixes sfu-dhil/wilde#142
update links for new content
Fix the search export.

Fix file name of one data table

---

LICENSE
compare-docs.html
compare.html
measure.html
modules/app.xql
package.json
resources/js/page/measure.js
yarn.lock

It was expecting a list of one or more nodes to compare, but if the item
being compared does not exist then it gets zero nodes and the
type-strictness throws an error. Allow zero or more nodes instead to avoid
the error.
Do the measure page entirely in JS so there's no server load.

Fix an error in find-similar().

---

modules/app.xql
modules/export.xql
modules/lang.xql

Use search filters in pagination and export.
